AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: URL Shortener API using AWS SAM

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 5
    MemorySize: 128
    Environment:
      Variables:
        JWT_SECRET: my-super-secret-key


Resources:
  UrlShortenerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UrlShortenerApi-CICD
      StageName: test
      EndpointConfiguration:
        Type: REGIONAL
      Cors:
        AllowMethods: "'GET,POST'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          JwtAuthorizer:
            FunctionArn: !GetAtt JwtAuthorizerFunction.Arn
            Identity:
              Header: Authorization

  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlTableNpl-CI-CD
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: shortId
          AttributeType: S
        - AttributeName: originalUrl
          AttributeType: S
      KeySchema:
        - AttributeName: shortId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: OriginalUrlIndex
          KeySchema:
            - AttributeName: originalUrl
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UsersTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL


  JwtAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: jwtAuthorizer.handler
      CodeUri: ./
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/authorizers/jwtAuthorizer.ts


  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: login.handler
      CodeUri: ./
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /login
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/functions/login.ts

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: register.handler
      CodeUri: ./
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
        - DynamoDBWritePolicy:
            TableName: !Ref UsersTable
      Events:
        RegisterApi:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /register
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/functions/register.ts


  CreateShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: createUrl.handler
      CodeUri: ./
      FunctionName: CreateShortUrlFunction-CICD
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlTable
          ORIGINAL_URL_INDEX: OriginalUrlIndex
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UrlTable
        - DynamoDBWritePolicy:
            TableName: !Ref UrlTable
      Events:
        CreateEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /get-url-shortner
            Method: POST
            Auth:
              Authorizer: JwtAuthorizer
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/functions/createUrl.ts

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: redirectUrl.handler
      CodeUri: ./
      FunctionName: RedirectFunction-CICD
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UrlTable
      Events:
        RedirectEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref UrlShortenerApi
            Path: /short/{shortId}
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        External:
          - '@aws-sdk/*'
        EntryPoints:
          - src/functions/redirectUrl.ts


Outputs:
  ApiUrl:
    Description: Base URL for API
    Value: !Sub 'https://${UrlShortenerApi}.execute-api.${AWS::Region}.amazonaws.com/test/'
